cc_binary(
    name = "step_1",
    srcs = ["step_1.cpp"],
    data = ["step_1.json"],
    deps = [
        "//C++/data_types:grid",
        "//C++/data_types:spatial_variable",
        "//C++/data_types:time_variable",
        "//C++/utilities:grid_generator",
        "@nlohmann_json//:json",
    ],
)
