"""
BUILD file for C++ data types tests.
"""

cc_test(
    name = "grid_tests",
    srcs = ["grid_tests.cpp"],
    deps = [
        "//CXX/data_types:grid",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "spatial_variable_tests",
    srcs = ["spatial_variable_tests.cpp"],
    deps = [
        "//CXX/data_types:spatial_variable",
        "@com_google_googletest//:gtest_main",
    ],
)
