cc_test(
    name = "grid_tests",
    srcs = ["grid_tests.cpp"],
    deps = [
        "//CXX/data_types:grid",
        "//CXX/utilities:grid_generator",
        "@com_google_googletest//:gtest_main",
    ],
)
