cc_test(
    name = "spatial_variable_tests",
    srcs = ["spatial_variable_tests.cpp"],
    deps = [
        "//C++/data_types:spatial_variable",
        "@com_google_googletest//:gtest_main",
    ],
)
