cc_test(
    name = "grid_tests",
    srcs = ["grid_tests.cpp"],
    deps = [
        "//C++/data_types:grid",
        "//C++/utilities:grid_generator",
        "@com_google_googletest//:gtest_main",
    ],
)
